<?php

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();

        Country::insert([
            ['short_name' => 'AF', 'name' => 'Afghanistan', 'iso3' => 'AFG', 'number_code' => '4', 'phone_code' => '93', 'is_default' => 'no'],
            ['short_name' => 'AL', 'name' => 'Albania', 'iso3' => 'ALB', 'number_code' => '8', 'phone_code' => '355', 'is_default' => 'no'],
            ['short_name' => 'DZ', 'name' => 'Algeria', 'iso3' => 'DZA', 'number_code' => '12', 'phone_code' => '213', 'is_default' => 'no'],
            ['short_name' => 'AS', 'name' => 'American Samoa', 'iso3' => 'ASM', 'number_code' => '16', 'phone_code' => '1684', 'is_default' => 'no'],
            ['short_name' => 'AD', 'name' => 'Andorra', 'iso3' => 'AND', 'number_code' => '20', 'phone_code' => '376', 'is_default' => 'no'],
            ['short_name' => 'AO', 'name' => 'Angola', 'iso3' => 'AGO', 'number_code' => '24', 'phone_code' => '244', 'is_default' => 'no'],
            ['short_name' => 'AI', 'name' => 'Anguilla', 'iso3' => 'AIA', 'number_code' => '660', 'phone_code' => '1264', 'is_default' => 'no'],
            ['short_name' => 'AQ', 'name' => 'Antarctica', 'iso3' => null, 'number_code' => null, 'phone_code' => '0', 'is_default' => 'no'],
            ['short_name' => 'AG', 'name' => 'Antigua and Barbuda', 'iso3' => 'ATG', 'number_code' => '28', 'phone_code' => '1268', 'is_default' => 'no'],
            ['short_name' => 'AR', 'name' => 'Argentina', 'iso3' => 'ARG', 'number_code' => '32', 'phone_code' => '54', 'is_default' => 'no'],
            ['short_name' => 'AM', 'name' => 'Armenia', 'iso3' => 'ARM', 'number_code' => '51', 'phone_code' => '374', 'is_default' => 'no'],
            ['short_name' => 'AW', 'name' => 'Aruba', 'iso3' => 'ABW', 'number_code' => '533', 'phone_code' => '297', 'is_default' => 'no'],
            ['short_name' => 'AU', 'name' => 'Australia', 'iso3' => 'AUS', 'number_code' => '36', 'phone_code' => '61', 'is_default' => 'no'],
            ['short_name' => 'AT', 'name' => 'Austria', 'iso3' => 'AUT', 'number_code' => '40', 'phone_code' => '43', 'is_default' => 'no'],
            ['short_name' => 'AZ', 'name' => 'Azerbaijan', 'iso3' => 'AZE', 'number_code' => '31', 'phone_code' => '994', 'is_default' => 'no'],
            ['short_name' => 'BS', 'name' => 'Bahamas', 'iso3' => 'BHS', 'number_code' => '44', 'phone_code' => '1242', 'is_default' => 'no'],
            ['short_name' => 'BH', 'name' => 'Bahrain', 'iso3' => 'BHR', 'number_code' => '48', 'phone_code' => '973', 'is_default' => 'no'],
            ['short_name' => 'BD', 'name' => 'Bangladesh', 'iso3' => 'BGD', 'number_code' => '50', 'phone_code' => '880', 'is_default' => 'no'],
            ['short_name' => 'BB', 'name' => 'Barbados', 'iso3' => 'BRB', 'number_code' => '52', 'phone_code' => '1246', 'is_default' => 'no'],
            ['short_name' => 'BY', 'name' => 'Belarus', 'iso3' => 'BLR', 'number_code' => '112', 'phone_code' => '375', 'is_default' => 'no'],
            ['short_name' => 'BE', 'name' => 'Belgium', 'iso3' => 'BEL', 'number_code' => '56', 'phone_code' => '32', 'is_default' => 'no'],
            ['short_name' => 'BZ', 'name' => 'Belize', 'iso3' => 'BLZ', 'number_code' => '84', 'phone_code' => '501', 'is_default' => 'no'],
            ['short_name' => 'BJ', 'name' => 'Benin', 'iso3' => 'BEN', 'number_code' => '204', 'phone_code' => '229', 'is_default' => 'no'],
            ['short_name' => 'BM', 'name' => 'Bermuda', 'iso3' => 'BMU', 'number_code' => '60', 'phone_code' => '1441', 'is_default' => 'no'],
            ['short_name' => 'BT', 'name' => 'Bhutan', 'iso3' => 'BTN', 'number_code' => '64', 'phone_code' => '975', 'is_default' => 'no'],
            ['short_name' => 'BO', 'name' => 'Bolivia', 'iso3' => 'BOL', 'number_code' => '68', 'phone_code' => '591', 'is_default' => 'no'],
            ['short_name' => 'BA', 'name' => 'Bosnia and Herzegovina', 'iso3' => 'BIH', 'number_code' => '70', 'phone_code' => '387', 'is_default' => 'no'],
            ['short_name' => 'BW', 'name' => 'Botswana', 'iso3' => 'BWA', 'number_code' => '72', 'phone_code' => '267', 'is_default' => 'no'],
            ['short_name' => 'BV', 'name' => 'Bouvet Island', 'iso3' => null, 'number_code' => null, 'phone_code' => '0', 'is_default' => 'no'],
            ['short_name' => 'BR', 'name' => 'Brazil', 'iso3' => 'BRA', 'number_code' => '76', 'phone_code' => '55', 'is_default' => 'no'],
            ['short_name' => 'IO', 'name' => 'British Indian Ocean Territory', 'iso3' => null, 'number_code' => null, 'phone_code' => '246', 'is_default' => 'no'],
            ['short_name' => 'BN', 'name' => 'Brunei Darussalam', 'iso3' => 'BRN', 'number_code' => '96', 'phone_code' => '673', 'is_default' => 'no'],
            ['short_name' => 'BG', 'name' => 'Bulgaria', 'iso3' => 'BGR', 'number_code' => '100', 'phone_code' => '359', 'is_default' => 'no'],
            ['short_name' => 'BF', 'name' => 'Burkina Faso', 'iso3' => 'BFA', 'number_code' => '854', 'phone_code' => '226', 'is_default' => 'no'],
            ['short_name' => 'BI', 'name' => 'Burundi', 'iso3' => 'BDI', 'number_code' => '108', 'phone_code' => '257', 'is_default' => 'no'],
            ['short_name' => 'KH', 'name' => 'Cambodia', 'iso3' => 'KHM', 'number_code' => '116', 'phone_code' => '855', 'is_default' => 'no'],
            ['short_name' => 'CM', 'name' => 'Cameroon', 'iso3' => 'CMR', 'number_code' => '120', 'phone_code' => '237', 'is_default' => 'no'],
            ['short_name' => 'CA', 'name' => 'Canada', 'iso3' => 'CAN', 'number_code' => '124', 'phone_code' => '1', 'is_default' => 'no'],
            ['short_name' => 'CV', 'name' => 'Cape Verde', 'iso3' => 'CPV', 'number_code' => '132', 'phone_code' => '238', 'is_default' => 'no'],
            ['short_name' => 'KY', 'name' => 'Cayman Islands', 'iso3' => 'CYM', 'number_code' => '136', 'phone_code' => '1345', 'is_default' => 'no'],
            ['short_name' => 'CF', 'name' => 'Central African Republic', 'iso3' => 'CAF', 'number_code' => '140', 'phone_code' => '236', 'is_default' => 'no'],
            ['short_name' => 'TD', 'name' => 'Chad', 'iso3' => 'TCD', 'number_code' => '148', 'phone_code' => '235', 'is_default' => 'no'],
            ['short_name' => 'CL', 'name' => 'Chile', 'iso3' => 'CHL', 'number_code' => '152', 'phone_code' => '56', 'is_default' => 'no'],
            ['short_name' => 'CN', 'name' => 'China', 'iso3' => 'CHN', 'number_code' => '156', 'phone_code' => '86', 'is_default' => 'no'],
            ['short_name' => 'CX', 'name' => 'Christmas Island', 'iso3' => null, 'number_code' => null, 'phone_code' => '61', 'is_default' => 'no'],
            ['short_name' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'iso3' => null, 'number_code' => null, 'phone_code' => '672', 'is_default' => 'no'],
            ['short_name' => 'CO', 'name' => 'Colombia', 'iso3' => 'COL', 'number_code' => '170', 'phone_code' => '57', 'is_default' => 'no'],
            ['short_name' => 'KM', 'name' => 'Comoros', 'iso3' => 'COM', 'number_code' => '174', 'phone_code' => '269', 'is_default' => 'no'],
            ['short_name' => 'CG', 'name' => 'Congo', 'iso3' => 'COG', 'number_code' => '178', 'phone_code' => '242', 'is_default' => 'no'],
            ['short_name' => 'CD', 'name' => 'Congo, the Democratic Republic of the', 'iso3' => 'COD', 'number_code' => '180', 'phone_code' => '242', 'is_default' => 'no'],
            ['short_name' => 'CK', 'name' => 'Cook Islands', 'iso3' => 'COK', 'number_code' => '184', 'phone_code' => '682', 'is_default' => 'no'],
            ['short_name' => 'CR', 'name' => 'Costa Rica', 'iso3' => 'CRI', 'number_code' => '188', 'phone_code' => '506', 'is_default' => 'no'],
            ['short_name' => 'CI', 'name' => 'Cote D\'Ivoire', 'iso3' => 'CIV', 'number_code' => '384', 'phone_code' => '225', 'is_default' => 'no'],
            ['short_name' => 'HR', 'name' => 'Croatia', 'iso3' => 'HRV', 'number_code' => '191', 'phone_code' => '385', 'is_default' => 'no'],
            ['short_name' => 'CU', 'name' => 'Cuba', 'iso3' => 'CUB', 'number_code' => '192', 'phone_code' => '53', 'is_default' => 'no'],
            ['short_name' => 'CY', 'name' => 'Cyprus', 'iso3' => 'CYP', 'number_code' => '196', 'phone_code' => '357', 'is_default' => 'no'],
            ['short_name' => 'CZ', 'name' => 'Czech Republic', 'iso3' => 'CZE', 'number_code' => '203', 'phone_code' => '420', 'is_default' => 'no'],
            ['short_name' => 'DK', 'name' => 'Denmark', 'iso3' => 'DNK', 'number_code' => '208', 'phone_code' => '45', 'is_default' => 'no'],
            ['short_name' => 'DJ', 'name' => 'Djibouti', 'iso3' => 'DJI', 'number_code' => '262', 'phone_code' => '253', 'is_default' => 'no'],
            ['short_name' => 'DM', 'name' => 'Dominica', 'iso3' => 'DMA', 'number_code' => '212', 'phone_code' => '1767', 'is_default' => 'no'],
            ['short_name' => 'DO', 'name' => 'Dominican Republic', 'iso3' => 'DOM', 'number_code' => '214', 'phone_code' => '1809', 'is_default' => 'no'],
            ['short_name' => 'EC', 'name' => 'Ecuador', 'iso3' => 'ECU', 'number_code' => '218', 'phone_code' => '593', 'is_default' => 'no'],
            ['short_name' => 'EG', 'name' => 'Egypt', 'iso3' => 'EGY', 'number_code' => '818', 'phone_code' => '20', 'is_default' => 'no'],
            ['short_name' => 'SV', 'name' => 'El Salvador', 'iso3' => 'SLV', 'number_code' => '222', 'phone_code' => '503', 'is_default' => 'no'],
            ['short_name' => 'GQ', 'name' => 'Equatorial Guinea', 'iso3' => 'GNQ', 'number_code' => '226', 'phone_code' => '240', 'is_default' => 'no'],
            ['short_name' => 'ER', 'name' => 'Eritrea', 'iso3' => 'ERI', 'number_code' => '232', 'phone_code' => '291', 'is_default' => 'no'],
            ['short_name' => 'EE', 'name' => 'Estonia', 'iso3' => 'EST', 'number_code' => '233', 'phone_code' => '372', 'is_default' => 'no'],
            ['short_name' => 'ET', 'name' => 'Ethiopia', 'iso3' => 'ETH', 'number_code' => '231', 'phone_code' => '251', 'is_default' => 'no'],
            ['short_name' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'iso3' => 'FLK', 'number_code' => '238', 'phone_code' => '500', 'is_default' => 'no'],
            ['short_name' => 'FO', 'name' => 'Faroe Islands', 'iso3' => 'FRO', 'number_code' => '234', 'phone_code' => '298', 'is_default' => 'no'],
            ['short_name' => 'FJ', 'name' => 'Fiji', 'iso3' => 'FJI', 'number_code' => '242', 'phone_code' => '679', 'is_default' => 'no'],
            ['short_name' => 'FI', 'name' => 'Finland', 'iso3' => 'FIN', 'number_code' => '246', 'phone_code' => '358', 'is_default' => 'no'],
            ['short_name' => 'FR', 'name' => 'France', 'iso3' => 'FRA', 'number_code' => '250', 'phone_code' => '33', 'is_default' => 'no'],
            ['short_name' => 'GF', 'name' => 'French Guiana', 'iso3' => 'GUF', 'number_code' => '254', 'phone_code' => '594', 'is_default' => 'no'],
            ['short_name' => 'PF', 'name' => 'French Polynesia', 'iso3' => 'PYF', 'number_code' => '258', 'phone_code' => '689', 'is_default' => 'no'],
            ['short_name' => 'TF', 'name' => 'French Southern Territories', 'iso3' => null, 'number_code' => null, 'phone_code' => '0', 'is_default' => 'no'],
            ['short_name' => 'GA', 'name' => 'Gabon', 'iso3' => 'GAB', 'number_code' => '266', 'phone_code' => '241', 'is_default' => 'no'],
            ['short_name' => 'GM', 'name' => 'Gambia', 'iso3' => 'GMB', 'number_code' => '270', 'phone_code' => '220', 'is_default' => 'no'],
            ['short_name' => 'GE', 'name' => 'Georgia', 'iso3' => 'GEO', 'number_code' => '268', 'phone_code' => '995', 'is_default' => 'no'],
            ['short_name' => 'DE', 'name' => 'Germany', 'iso3' => 'DEU', 'number_code' => '276', 'phone_code' => '49', 'is_default' => 'no'],
            ['short_name' => 'GH', 'name' => 'Ghana', 'iso3' => 'GHA', 'number_code' => '288', 'phone_code' => '233', 'is_default' => 'no'],
            ['short_name' => 'GI', 'name' => 'Gibraltar', 'iso3' => 'GIB', 'number_code' => '292', 'phone_code' => '350', 'is_default' => 'no'],
            ['short_name' => 'GR', 'name' => 'Greece', 'iso3' => 'GRC', 'number_code' => '300', 'phone_code' => '30', 'is_default' => 'no'],
            ['short_name' => 'GL', 'name' => 'Greenland', 'iso3' => 'GRL', 'number_code' => '304', 'phone_code' => '299', 'is_default' => 'no'],
            ['short_name' => 'GD', 'name' => 'Grenada', 'iso3' => 'GRD', 'number_code' => '308', 'phone_code' => '1473', 'is_default' => 'no'],
            ['short_name' => 'GP', 'name' => 'Guadeloupe', 'iso3' => 'GLP', 'number_code' => '312', 'phone_code' => '590', 'is_default' => 'no'],
            ['short_name' => 'GU', 'name' => 'Guam', 'iso3' => 'GUM', 'number_code' => '316', 'phone_code' => '1671', 'is_default' => 'no'],
            ['short_name' => 'GT', 'name' => 'Guatemala', 'iso3' => 'GTM', 'number_code' => '320', 'phone_code' => '502', 'is_default' => 'no'],
            ['short_name' => 'GN', 'name' => 'Guinea', 'iso3' => 'GIN', 'number_code' => '324', 'phone_code' => '224', 'is_default' => 'no'],
            ['short_name' => 'GW', 'name' => 'Guinea-Bissau', 'iso3' => 'GNB', 'number_code' => '624', 'phone_code' => '245', 'is_default' => 'no'],
            ['short_name' => 'GY', 'name' => 'Guyana', 'iso3' => 'GUY', 'number_code' => '328', 'phone_code' => '592', 'is_default' => 'no'],
            ['short_name' => 'HT', 'name' => 'Haiti', 'iso3' => 'HTI', 'number_code' => '332', 'phone_code' => '509', 'is_default' => 'no'],
            ['short_name' => 'HM', 'name' => 'Heard Island and Mcdonald Islands', 'iso3' => null, 'number_code' => null, 'phone_code' => '0', 'is_default' => 'no'],
            ['short_name' => 'VA', 'name' => 'Holy See (Vatican City State)', 'iso3' => 'VAT', 'number_code' => '336', 'phone_code' => '39', 'is_default' => 'no'],
            ['short_name' => 'HN', 'name' => 'Honduras', 'iso3' => 'HND', 'number_code' => '340', 'phone_code' => '504', 'is_default' => 'no'],
            ['short_name' => 'HK', 'name' => 'Hong Kong', 'iso3' => 'HKG', 'number_code' => '344', 'phone_code' => '852', 'is_default' => 'no'],
            ['short_name' => 'HU', 'name' => 'Hungary', 'iso3' => 'HUN', 'number_code' => '348', 'phone_code' => '36', 'is_default' => 'no'],
            ['short_name' => 'IS', 'name' => 'Iceland', 'iso3' => 'ISL', 'number_code' => '352', 'phone_code' => '354', 'is_default' => 'no'],
            ['short_name' => 'IN', 'name' => 'India', 'iso3' => 'IND', 'number_code' => '356', 'phone_code' => '91', 'is_default' => 'no'],
            ['short_name' => 'ID', 'name' => 'Indonesia', 'iso3' => 'IDN', 'number_code' => '360', 'phone_code' => '62', 'is_default' => 'no'],
            ['short_name' => 'IR', 'name' => 'Iran, Islamic Republic of', 'iso3' => 'IRN', 'number_code' => '364', 'phone_code' => '98', 'is_default' => 'no'],
            ['short_name' => 'IQ', 'name' => 'Iraq', 'iso3' => 'IRQ', 'number_code' => '368', 'phone_code' => '964', 'is_default' => 'no'],
            ['short_name' => 'IE', 'name' => 'Ireland', 'iso3' => 'IRL', 'number_code' => '372', 'phone_code' => '353', 'is_default' => 'no'],
            ['short_name' => 'IL', 'name' => 'Israel', 'iso3' => 'ISR', 'number_code' => '376', 'phone_code' => '972', 'is_default' => 'no'],
            ['short_name' => 'IT', 'name' => 'Italy', 'iso3' => 'ITA', 'number_code' => '380', 'phone_code' => '39', 'is_default' => 'no'],
            ['short_name' => 'JM', 'name' => 'Jamaica', 'iso3' => 'JAM', 'number_code' => '388', 'phone_code' => '1876', 'is_default' => 'no'],
            ['short_name' => 'JP', 'name' => 'Japan', 'iso3' => 'JPN', 'number_code' => '392', 'phone_code' => '81', 'is_default' => 'no'],
            ['short_name' => 'JO', 'name' => 'Jordan', 'iso3' => 'JOR', 'number_code' => '400', 'phone_code' => '962', 'is_default' => 'no'],
            ['short_name' => 'KZ', 'name' => 'Kazakhstan', 'iso3' => 'KAZ', 'number_code' => '398', 'phone_code' => '7', 'is_default' => 'no'],
            ['short_name' => 'KE', 'name' => 'Kenya', 'iso3' => 'KEN', 'number_code' => '404', 'phone_code' => '254', 'is_default' => 'no'],
            ['short_name' => 'KI', 'name' => 'Kiribati', 'iso3' => 'KIR', 'number_code' => '296', 'phone_code' => '686', 'is_default' => 'no'],
            ['short_name' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'iso3' => 'PRK', 'number_code' => '408', 'phone_code' => '850', 'is_default' => 'no'],
            ['short_name' => 'KR', 'name' => 'Korea, Republic of', 'iso3' => 'KOR', 'number_code' => '410', 'phone_code' => '82', 'is_default' => 'no'],
            ['short_name' => 'KW', 'name' => 'Kuwait', 'iso3' => 'KWT', 'number_code' => '414', 'phone_code' => '965', 'is_default' => 'no'],
            ['short_name' => 'KG', 'name' => 'Kyrgyzstan', 'iso3' => 'KGZ', 'number_code' => '417', 'phone_code' => '996', 'is_default' => 'no'],
            ['short_name' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'iso3' => 'LAO', 'number_code' => '418', 'phone_code' => '856', 'is_default' => 'no'],
            ['short_name' => 'LV', 'name' => 'Latvia', 'iso3' => 'LVA', 'number_code' => '428', 'phone_code' => '371', 'is_default' => 'no'],
            ['short_name' => 'LB', 'name' => 'Lebanon', 'iso3' => 'LBN', 'number_code' => '422', 'phone_code' => '961', 'is_default' => 'no'],
            ['short_name' => 'LS', 'name' => 'Lesotho', 'iso3' => 'LSO', 'number_code' => '426', 'phone_code' => '266', 'is_default' => 'no'],
            ['short_name' => 'LR', 'name' => 'Liberia', 'iso3' => 'LBR', 'number_code' => '430', 'phone_code' => '231', 'is_default' => 'no'],
            ['short_name' => 'LY', 'name' => 'Libyan Arab Jamahiriya', 'iso3' => 'LBY', 'number_code' => '434', 'phone_code' => '218', 'is_default' => 'no'],
            ['short_name' => 'LI', 'name' => 'Liechtenstein', 'iso3' => 'LIE', 'number_code' => '438', 'phone_code' => '423', 'is_default' => 'no'],
            ['short_name' => 'LT', 'name' => 'Lithuania', 'iso3' => 'LTU', 'number_code' => '440', 'phone_code' => '370', 'is_default' => 'no'],
            ['short_name' => 'LU', 'name' => 'Luxembourg', 'iso3' => 'LUX', 'number_code' => '442', 'phone_code' => '352', 'is_default' => 'no'],
            ['short_name' => 'MO', 'name' => 'Macao', 'iso3' => 'MAC', 'number_code' => '446', 'phone_code' => '853', 'is_default' => 'no'],
            ['short_name' => 'MK', 'name' => 'Macedonia, the Former Yugoslav Republic of', 'iso3' => 'MKD', 'number_code' => '807', 'phone_code' => '389', 'is_default' => 'no'],
            ['short_name' => 'MG', 'name' => 'Madagascar', 'iso3' => 'MDG', 'number_code' => '450', 'phone_code' => '261', 'is_default' => 'no'],
            ['short_name' => 'MW', 'name' => 'Malawi', 'iso3' => 'MWI', 'number_code' => '454', 'phone_code' => '265', 'is_default' => 'no'],
            ['short_name' => 'MY', 'name' => 'Malaysia', 'iso3' => 'MYS', 'number_code' => '458', 'phone_code' => '60', 'is_default' => 'no'],
            ['short_name' => 'MV', 'name' => 'Maldives', 'iso3' => 'MDV', 'number_code' => '462', 'phone_code' => '960', 'is_default' => 'no'],
            ['short_name' => 'ML', 'name' => 'Mali', 'iso3' => 'MLI', 'number_code' => '466', 'phone_code' => '223', 'is_default' => 'no'],
            ['short_name' => 'MT', 'name' => 'Malta', 'iso3' => 'MLT', 'number_code' => '470', 'phone_code' => '356', 'is_default' => 'no'],
            ['short_name' => 'MH', 'name' => 'Marshall Islands', 'iso3' => 'MHL', 'number_code' => '584', 'phone_code' => '692', 'is_default' => 'no'],
            ['short_name' => 'MQ', 'name' => 'Martinique', 'iso3' => 'MTQ', 'number_code' => '474', 'phone_code' => '596', 'is_default' => 'no'],
            ['short_name' => 'MR', 'name' => 'Mauritania', 'iso3' => 'MRT', 'number_code' => '478', 'phone_code' => '222', 'is_default' => 'no'],
            ['short_name' => 'MU', 'name' => 'Mauritius', 'iso3' => 'MUS', 'number_code' => '480', 'phone_code' => '230', 'is_default' => 'no'],
            ['short_name' => 'YT', 'name' => 'Mayotte', 'iso3' => null, 'number_code' => null, 'phone_code' => '269', 'is_default' => 'no'],
            ['short_name' => 'MX', 'name' => 'Mexico', 'iso3' => 'MEX', 'number_code' => '484', 'phone_code' => '52', 'is_default' => 'no'],
            ['short_name' => 'FM', 'name' => 'Micronesia, Federated States of', 'iso3' => 'FSM', 'number_code' => '583', 'phone_code' => '691', 'is_default' => 'no'],
            ['short_name' => 'MD', 'name' => 'Moldova, Republic of', 'iso3' => 'MDA', 'number_code' => '498', 'phone_code' => '373', 'is_default' => 'no'],
            ['short_name' => 'MC', 'name' => 'Monaco', 'iso3' => 'MCO', 'number_code' => '492', 'phone_code' => '377', 'is_default' => 'no'],
            ['short_name' => 'MN', 'name' => 'Mongolia', 'iso3' => 'MNG', 'number_code' => '496', 'phone_code' => '976', 'is_default' => 'no'],
            ['short_name' => 'MS', 'name' => 'Montserrat', 'iso3' => 'MSR', 'number_code' => '500', 'phone_code' => '1664', 'is_default' => 'no'],
            ['short_name' => 'MA', 'name' => 'Morocco', 'iso3' => 'MAR', 'number_code' => '504', 'phone_code' => '212', 'is_default' => 'no'],
            ['short_name' => 'MZ', 'name' => 'Mozambique', 'iso3' => 'MOZ', 'number_code' => '508', 'phone_code' => '258', 'is_default' => 'no'],
            ['short_name' => 'MM', 'name' => 'Myanmar', 'iso3' => 'MMR', 'number_code' => '104', 'phone_code' => '95', 'is_default' => 'no'],
            ['short_name' => 'NA', 'name' => 'Namibia', 'iso3' => 'NAM', 'number_code' => '516', 'phone_code' => '264', 'is_default' => 'no'],
            ['short_name' => 'NR', 'name' => 'Nauru', 'iso3' => 'NRU', 'number_code' => '520', 'phone_code' => '674', 'is_default' => 'no'],
            ['short_name' => 'NP', 'name' => 'Nepal', 'iso3' => 'NPL', 'number_code' => '524', 'phone_code' => '977', 'is_default' => 'no'],
            ['short_name' => 'NL', 'name' => 'Netherlands', 'iso3' => 'NLD', 'number_code' => '528', 'phone_code' => '31', 'is_default' => 'no'],
            ['short_name' => 'AN', 'name' => 'Netherlands Antilles', 'iso3' => 'ANT', 'number_code' => '530', 'phone_code' => '599', 'is_default' => 'no'],
            ['short_name' => 'NC', 'name' => 'New Caledonia', 'iso3' => 'NCL', 'number_code' => '540', 'phone_code' => '687', 'is_default' => 'no'],
            ['short_name' => 'NZ', 'name' => 'New Zealand', 'iso3' => 'NZL', 'number_code' => '554', 'phone_code' => '64', 'is_default' => 'no'],
            ['short_name' => 'NI', 'name' => 'Nicaragua', 'iso3' => 'NIC', 'number_code' => '558', 'phone_code' => '505', 'is_default' => 'no'],
            ['short_name' => 'NE', 'name' => 'Niger', 'iso3' => 'NER', 'number_code' => '562', 'phone_code' => '227', 'is_default' => 'no'],
            ['short_name' => 'NG', 'name' => 'Nigeria', 'iso3' => 'NGA', 'number_code' => '566', 'phone_code' => '234', 'is_default' => 'no'],
            ['short_name' => 'NU', 'name' => 'Niue', 'iso3' => 'NIU', 'number_code' => '570', 'phone_code' => '683', 'is_default' => 'no'],
            ['short_name' => 'NF', 'name' => 'Norfolk Island', 'iso3' => 'NFK', 'number_code' => '574', 'phone_code' => '672', 'is_default' => 'no'],
            ['short_name' => 'MP', 'name' => 'Northern Mariana Islands', 'iso3' => 'MNP', 'number_code' => '580', 'phone_code' => '1670', 'is_default' => 'no'],
            ['short_name' => 'NO', 'name' => 'Norway', 'iso3' => 'NOR', 'number_code' => '578', 'phone_code' => '47', 'is_default' => 'no'],
            ['short_name' => 'OM', 'name' => 'Oman', 'iso3' => 'OMN', 'number_code' => '512', 'phone_code' => '968', 'is_default' => 'no'],
            ['short_name' => 'PK', 'name' => 'Pakistan', 'iso3' => 'PAK', 'number_code' => '586', 'phone_code' => '92', 'is_default' => 'no'],
            ['short_name' => 'PW', 'name' => 'Palau', 'iso3' => 'PLW', 'number_code' => '585', 'phone_code' => '680', 'is_default' => 'no'],
            ['short_name' => 'PS', 'name' => 'Palestinian Territory, Occupied', 'iso3' => null, 'number_code' => null, 'phone_code' => '970', 'is_default' => 'no'],
            ['short_name' => 'PA', 'name' => 'Panama', 'iso3' => 'PAN', 'number_code' => '591', 'phone_code' => '507', 'is_default' => 'no'],
            ['short_name' => 'PG', 'name' => 'Papua New Guinea', 'iso3' => 'PNG', 'number_code' => '598', 'phone_code' => '675', 'is_default' => 'no'],
            ['short_name' => 'PY', 'name' => 'Paraguay', 'iso3' => 'PRY', 'number_code' => '600', 'phone_code' => '595', 'is_default' => 'no'],
            ['short_name' => 'PE', 'name' => 'Peru', 'iso3' => 'PER', 'number_code' => '604', 'phone_code' => '51', 'is_default' => 'no'],
            ['short_name' => 'PH', 'name' => 'Philippines', 'iso3' => 'PHL', 'number_code' => '608', 'phone_code' => '63', 'is_default' => 'no'],
            ['short_name' => 'PN', 'name' => 'Pitcairn', 'iso3' => 'PCN', 'number_code' => '612', 'phone_code' => '0', 'is_default' => 'no'],
            ['short_name' => 'PL', 'name' => 'Poland', 'iso3' => 'POL', 'number_code' => '616', 'phone_code' => '48', 'is_default' => 'no'],
            ['short_name' => 'PT', 'name' => 'Portugal', 'iso3' => 'PRT', 'number_code' => '620', 'phone_code' => '351', 'is_default' => 'no'],
            ['short_name' => 'PR', 'name' => 'Puerto Rico', 'iso3' => 'PRI', 'number_code' => '630', 'phone_code' => '1787', 'is_default' => 'no'],
            ['short_name' => 'QA', 'name' => 'Qatar', 'iso3' => 'QAT', 'number_code' => '634', 'phone_code' => '974', 'is_default' => 'no'],
            ['short_name' => 'RE', 'name' => 'Reunion', 'iso3' => 'REU', 'number_code' => '638', 'phone_code' => '262', 'is_default' => 'no'],
            ['short_name' => 'RO', 'name' => 'Romania', 'iso3' => 'ROM', 'number_code' => '642', 'phone_code' => '40', 'is_default' => 'no'],
            ['short_name' => 'RU', 'name' => 'Russian Federation', 'iso3' => 'RUS', 'number_code' => '643', 'phone_code' => '70', 'is_default' => 'no'],
            ['short_name' => 'RW', 'name' => 'Rwanda', 'iso3' => 'RWA', 'number_code' => '646', 'phone_code' => '250', 'is_default' => 'no'],
            ['short_name' => 'SH', 'name' => 'Saint Helena', 'iso3' => 'SHN', 'number_code' => '654', 'phone_code' => '290', 'is_default' => 'no'],
            ['short_name' => 'KN', 'name' => 'Saint Kitts and Nevis', 'iso3' => 'KNA', 'number_code' => '659', 'phone_code' => '1869', 'is_default' => 'no'],
            ['short_name' => 'LC', 'name' => 'Saint Lucia', 'iso3' => 'LCA', 'number_code' => '662', 'phone_code' => '1758', 'is_default' => 'no'],
            ['short_name' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'iso3' => 'SPM', 'number_code' => '666', 'phone_code' => '508', 'is_default' => 'no'],
            ['short_name' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'iso3' => 'VCT', 'number_code' => '670', 'phone_code' => '1784', 'is_default' => 'no'],
            ['short_name' => 'WS', 'name' => 'Samoa', 'iso3' => 'WSM', 'number_code' => '882', 'phone_code' => '684', 'is_default' => 'no'],
            ['short_name' => 'SM', 'name' => 'San Marino', 'iso3' => 'SMR', 'number_code' => '674', 'phone_code' => '378', 'is_default' => 'no'],
            ['short_name' => 'ST', 'name' => 'Sao Tome and Principe', 'iso3' => 'STP', 'number_code' => '678', 'phone_code' => '239', 'is_default' => 'no'],
            ['short_name' => 'SA', 'name' => 'Saudi Arabia', 'iso3' => 'SAU', 'number_code' => '682', 'phone_code' => '966', 'is_default' => 'no'],
            ['short_name' => 'SN', 'name' => 'Senegal', 'iso3' => 'SEN', 'number_code' => '686', 'phone_code' => '221', 'is_default' => 'no'],
            ['short_name' => 'CS', 'name' => 'Serbia and Montenegro', 'iso3' => null, 'number_code' => null, 'phone_code' => '381', 'is_default' => 'no'],
            ['short_name' => 'SC', 'name' => 'Seychelles', 'iso3' => 'SYC', 'number_code' => '690', 'phone_code' => '248', 'is_default' => 'no'],
            ['short_name' => 'SL', 'name' => 'Sierra Leone', 'iso3' => 'SLE', 'number_code' => '694', 'phone_code' => '232', 'is_default' => 'no'],
            ['short_name' => 'SG', 'name' => 'Singapore', 'iso3' => 'SGP', 'number_code' => '702', 'phone_code' => '65', 'is_default' => 'no'],
            ['short_name' => 'SK', 'name' => 'Slovakia', 'iso3' => 'SVK', 'number_code' => '703', 'phone_code' => '421', 'is_default' => 'no'],
            ['short_name' => 'SI', 'name' => 'Slovenia', 'iso3' => 'SVN', 'number_code' => '705', 'phone_code' => '386', 'is_default' => 'no'],
            ['short_name' => 'SB', 'name' => 'Solomon Islands', 'iso3' => 'SLB', 'number_code' => '90', 'phone_code' => '677', 'is_default' => 'no'],
            ['short_name' => 'SO', 'name' => 'Somalia', 'iso3' => 'SOM', 'number_code' => '706', 'phone_code' => '252', 'is_default' => 'no'],
            ['short_name' => 'ZA', 'name' => 'South Africa', 'iso3' => 'ZAF', 'number_code' => '710', 'phone_code' => '27', 'is_default' => 'no'],
            ['short_name' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands', 'iso3' => null, 'number_code' => null, 'phone_code' => '0', 'is_default' => 'no'],
            ['short_name' => 'ES', 'name' => 'Spain', 'iso3' => 'ESP', 'number_code' => '724', 'phone_code' => '34', 'is_default' => 'no'],
            ['short_name' => 'LK', 'name' => 'Sri Lanka', 'iso3' => 'LKA', 'number_code' => '144', 'phone_code' => '94', 'is_default' => 'no'],
            ['short_name' => 'SD', 'name' => 'Sudan', 'iso3' => 'SDN', 'number_code' => '736', 'phone_code' => '249', 'is_default' => 'no'],
            ['short_name' => 'SR', 'name' => 'Suriname', 'iso3' => 'SUR', 'number_code' => '740', 'phone_code' => '597', 'is_default' => 'no'],
            ['short_name' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'iso3' => 'SJM', 'number_code' => '744', 'phone_code' => '47', 'is_default' => 'no'],
            ['short_name' => 'SZ', 'name' => 'Swaziland', 'iso3' => 'SWZ', 'number_code' => '748', 'phone_code' => '268', 'is_default' => 'no'],
            ['short_name' => 'SE', 'name' => 'Sweden', 'iso3' => 'SWE', 'number_code' => '752', 'phone_code' => '46', 'is_default' => 'no'],
            ['short_name' => 'CH', 'name' => 'Switzerland', 'iso3' => 'CHE', 'number_code' => '756', 'phone_code' => '41', 'is_default' => 'no'],
            ['short_name' => 'SY', 'name' => 'Syrian Arab Republic', 'iso3' => 'SYR', 'number_code' => '760', 'phone_code' => '963', 'is_default' => 'no'],
            ['short_name' => 'TW', 'name' => 'Taiwan, Province of China', 'iso3' => 'TWN', 'number_code' => '158', 'phone_code' => '886', 'is_default' => 'no'],
            ['short_name' => 'TJ', 'name' => 'Tajikistan', 'iso3' => 'TJK', 'number_code' => '762', 'phone_code' => '992', 'is_default' => 'no'],
            ['short_name' => 'TZ', 'name' => 'Tanzania, United Republic of', 'iso3' => 'TZA', 'number_code' => '834', 'phone_code' => '255', 'is_default' => 'no'],
            ['short_name' => 'TH', 'name' => 'Thailand', 'iso3' => 'THA', 'number_code' => '764', 'phone_code' => '66', 'is_default' => 'no'],
            ['short_name' => 'TL', 'name' => 'Timor-Leste', 'iso3' => null, 'number_code' => null, 'phone_code' => '670', 'is_default' => 'no'],
            ['short_name' => 'TG', 'name' => 'Togo', 'iso3' => 'TGO', 'number_code' => '768', 'phone_code' => '228', 'is_default' => 'no'],
            ['short_name' => 'TK', 'name' => 'Tokelau', 'iso3' => 'TKL', 'number_code' => '772', 'phone_code' => '690', 'is_default' => 'no'],
            ['short_name' => 'TO', 'name' => 'Tonga', 'iso3' => 'TON', 'number_code' => '776', 'phone_code' => '676', 'is_default' => 'no'],
            ['short_name' => 'TT', 'name' => 'Trinidad and Tobago', 'iso3' => 'TTO', 'number_code' => '780', 'phone_code' => '1868', 'is_default' => 'no'],
            ['short_name' => 'TN', 'name' => 'Tunisia', 'iso3' => 'TUN', 'number_code' => '788', 'phone_code' => '216', 'is_default' => 'no'],
            ['short_name' => 'TR', 'name' => 'Turkey', 'iso3' => 'TUR', 'number_code' => '792', 'phone_code' => '90', 'is_default' => 'no'],
            ['short_name' => 'TM', 'name' => 'Turkmenistan', 'iso3' => 'TKM', 'number_code' => '795', 'phone_code' => '7370', 'is_default' => 'no'],
            ['short_name' => 'TC', 'name' => 'Turks and Caicos Islands', 'iso3' => 'TCA', 'number_code' => '796', 'phone_code' => '1649', 'is_default' => 'no'],
            ['short_name' => 'TV', 'name' => 'Tuvalu', 'iso3' => 'TUV', 'number_code' => '798', 'phone_code' => '688', 'is_default' => 'no'],
            ['short_name' => 'UG', 'name' => 'Uganda', 'iso3' => 'UGA', 'number_code' => '800', 'phone_code' => '256', 'is_default' => 'no'],
            ['short_name' => 'UA', 'name' => 'Ukraine', 'iso3' => 'UKR', 'number_code' => '804', 'phone_code' => '380', 'is_default' => 'no'],
            ['short_name' => 'AE', 'name' => 'United Arab Emirates', 'iso3' => 'ARE', 'number_code' => '784', 'phone_code' => '971', 'is_default' => 'no'],
            ['short_name' => 'GB', 'name' => 'United Kingdom', 'iso3' => 'GBR', 'number_code' => '826', 'phone_code' => '44', 'is_default' => 'no'],
            ['short_name' => 'US', 'name' => 'United States', 'iso3' => 'USA', 'number_code' => '840', 'phone_code' => '1', 'is_default' => 'yes'],
            ['short_name' => 'UM', 'name' => 'United States Minor Outlying Islands', 'iso3' => null, 'number_code' => null, 'phone_code' => '1', 'is_default' => 'no'],
            ['short_name' => 'UY', 'name' => 'Uruguay', 'iso3' => 'URY', 'number_code' => '858', 'phone_code' => '598', 'is_default' => 'no'],
            ['short_name' => 'UZ', 'name' => 'Uzbekistan', 'iso3' => 'UZB', 'number_code' => '860', 'phone_code' => '998', 'is_default' => 'no'],
            ['short_name' => 'VU', 'name' => 'Vanuatu', 'iso3' => 'VUT', 'number_code' => '548', 'phone_code' => '678', 'is_default' => 'no'],
            ['short_name' => 'VE', 'name' => 'Venezuela', 'iso3' => 'VEN', 'number_code' => '862', 'phone_code' => '58', 'is_default' => 'no'],
            ['short_name' => 'VN', 'name' => 'Viet Nam', 'iso3' => 'VNM', 'number_code' => '704', 'phone_code' => '84', 'is_default' => 'no'],
            ['short_name' => 'VG', 'name' => 'Virgin Islands, British', 'iso3' => 'VGB', 'number_code' => '92', 'phone_code' => '1284', 'is_default' => 'no'],
            ['short_name' => 'VI', 'name' => 'Virgin Islands, U.s.', 'iso3' => 'VIR', 'number_code' => '850', 'phone_code' => '1340', 'is_default' => 'no'],
            ['short_name' => 'WF', 'name' => 'Wallis and Futuna', 'iso3' => 'WLF', 'number_code' => '876', 'phone_code' => '681', 'is_default' => 'no'],
            ['short_name' => 'EH', 'name' => 'Western Sahara', 'iso3' => 'ESH', 'number_code' => '732', 'phone_code' => '212', 'is_default' => 'no'],
            ['short_name' => 'YE', 'name' => 'Yemen', 'iso3' => 'YEM', 'number_code' => '887', 'phone_code' => '967', 'is_default' => 'no'],
            ['short_name' => 'ZM', 'name' => 'Zambia', 'iso3' => 'ZMB', 'number_code' => '894', 'phone_code' => '260', 'is_default' => 'no'],
            ['short_name' => 'ZW', 'name' => 'Zimbabwe', 'iso3' => 'ZWE', 'number_code' => '716', 'phone_code' => '263', 'is_default' => 'no'],
        ]);
    }
}
